spring:
  application:
    name: nhn-academy-mini-dooray
  datasource:
    url: jdbc:mysql://133.186.241.167:3306/nhn_academy_110?useSSL=false&serverTimezone=UTC
    username: nhn_academy_110
    password: rP4noigu!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

