spring:
  profiles:
    active: dev
  application:
    name: nhn-academy-mini-dooray
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:sql/data.sql

---
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://133.186.241.167:3306/nhn_academy_110?useSSL=false&serverTimezone=UTC
    username: nhn_academy_110
    password: rP4noigu!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


